name: Build and Run Faktorialis Program

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Kód klónozása
      uses: actions/checkout@v3

    - name: C++ fordító telepítése
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Faktoriális program buildelése
      run: |
        g++ faktorialis.cpp -o faktorialis
        echo "Build sikeres!"

    - name: Program futtatása
      run: ./faktorialis
