name: Build and Test Faktorialis Program

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Kód klónozása
      uses: actions/checkout@v3

    - name: C++ fordító telepítése
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Faktoriális program és teszt buildelése
      run: |
        g++ faktorialis.cpp faktorialis_test.cpp -o faktorialis_test
        echo "Build sikeres!"

    - name: Teszt futtatása
      run: ./faktorialis_test
